# -*- coding: utf-8 -*-
"""Dlab.week2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UejOQmiyLVIEfyDuM8xqe0-gXVHwqAoA

arry 테스트
"""

import numpy as np
list = [1,2,3,4,5]
print(list)
arr = np.array(list)
print(arr)

"""array 같은 종류

"""

arr = np.array([1,'a',3])
print(arr)

arr = np.array([1,2,0.3])
print(arr)

"""array 인덱싱 슬라이싱

"""

arr = np.array([1,2,3,4,5])
arr[2]

arr[-3]

arr = np.array([2,6,8,9,12,23,27,32,35])
arr[0:8:2]

arr[::2]

arr[:-1]

arr[-1:]

"""array 모양

"""

arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr2)

print(arr1.shape)
print(arr2.shape)

"""랜덤"""

np.random.random((2,3))

np.random.randint(0,100,size=(2,3))

"""일정한 배열"""

np.arange(1,11)

np.arange(1,2,0.1)

"""numpy 기본연산"""

arr1 = np.array([2,4,6,8,10])
arr2 = np.array([5,10,15,20,25])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

"""where 필터링"""

arr = np.array([38,16,1,27,55,8,19])
print(np.where(arr>20))

"""sort 배열 정렬"""

np.sort(arr)

np.sort(arr)[::-1] #거꾸로 정렬

"""마무리 미션
(일 매출 분석)
"""

c = [87,63,64,110,144,143,69,53,133,55,78,123,63,101]
w = [87,36,32,101,41,78,115,31,53,11,13,119,25,65]

c = np.array(c) *3400
w = np.array(w) *6700
print(c)
print(w)

"""총 매출 평균 매출"""

p = np.sum(c)
print(p)
s = p/14
print(s)


p1 = np.sum(w)
print(p1)
s1 = p1/14
print(s1)

"""일별 총매출"""

day = c+w
print(day)

"""카페에 일별 매출이 450,000을 넘지 못한날, 가격과 인덱스 번호"""

f= np.where(day<=450000)

print(day[f], f)